In [23]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
from scipy.stats import linregress,pearsonr
import numpy as np

In [24]:
covid_df = pd.read_csv('Resources/covid19cases_test.csv')
covid_df

,date,area,area_type,population,cases,deaths,total_tests,positive_tests,reported_cases,reported_deaths,reported_tests
0,2021-04-25,Alameda,County,1685886.0,0.0,0.0,NaN,NaN,146.0,-1.0,10474.0
1,2021-04-25,Alpine,County,1117.0,0.0,0.0,NaN,NaN,1.0,0.0,4.0
2,2021-04-25,Amador,County,38531.0,0.0,0.0,NaN,NaN,3.0,0.0,701.0
3,2021-04-25,Butte,County,217769.0,0.0,0.0,NaN,NaN,31.0,0.0,936.0
4,2021-04-25,Calaveras,County,44289.0,0.0,0.0,NaN,NaN,5.0,0.0,155.0
...,...,...,...,...,...,...,...,...,...,...,...
27445,2020-02-01,Tuolumne,County,52351.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN
27446,2020-02-01,Unknown,County,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN
27447,2020-02-01,Ventura,County,852747.0,NaN,NaN,1.0,0.0,0.0,0.0,NaN
27448,2020-02-01,Yolo,County,223612.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN
27449,2020-02-01,Yuba,County,79290.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN

In [30]:
cases_df = covid_df.groupby('cases')['area'].count()

cases_df

cases
0.0        4808
1.0        1500
2.0        1007
3.0         803
4.0         663
           ...
54325.0       1
54852.0       1
57732.0       1
58742.0       1
60218.0       1
Name: area, Length: 1798, dtype: int64

In [ ]:
covid_df['area']